import { rubik } from '@/app/ui/fonts'
import './globals.css'
import NavBar from '@/app/ui/components/Navbar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${rubik.className} antialiased`}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
