import { rubik, robotoMono } from '@/app/ui/fonts'
import './globals.css'

export const metadata = {
  title: 'Óscar Sancho Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body className={`${rubik.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
